version: '3'

services:
  # survey:
  #   build: survey_server/
  #   depends_on:
  #     - 'database'
  #   ports: 
  #     - '8080:8080'

  api:
    build: api/
    # depends_on:
    #   - 'database'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/src/app
      - /src/app/node_modules

  # database:
  #   image: mongo:latest
