version: '3'

services:
  frontend:
    build: libraryfrontend/
    # depends_on:
    #   - 'database'
    ports: 
      - '3001:3000'

  api:
    build: api/
    # depends_on:
    #   - 'database'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/src/app
      - /src/app/node_modules

  #  db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  # database:
  #   image: mongo:latest
